<?php

// autoload_classmap.php @generated by TYPO3

$typo3InstallDir = \TYPO3\CMS\Core\Core\Environment::getPublicPath() . '/';

return array(
    'BK2K\\BootstrapPackage\\' => array($typo3InstallDir . 'typo3conf/ext/bootstrap_package/Classes'),
    'Bobosch\\OdsOsm\\' => array($typo3InstallDir . 'typo3conf/ext/ods_osm/Classes'),
    'FriendsOfTYPO3\\FontawesomeProvider\\' => array($typo3InstallDir . 'typo3conf/ext/fontawesome_provider/Classes'),
    'FriendsOfTYPO3\\TtAddress\\' => array($typo3InstallDir . 'typo3conf/ext/tt_address/Classes'),
    'In2code\\Powermail\\' => array($typo3InstallDir . 'typo3conf/ext/powermail/Classes'),
    'MASK\\Mask\\' => array($typo3InstallDir . 'typo3conf/ext/mask/Classes'),
    'TYPO3\\CMS\\Introduction\\' => array($typo3InstallDir . 'typo3conf/ext/introduction/Classes'),
    'Tpwd\\KeSearch\\' => array($typo3InstallDir . 'typo3conf/ext/ke_search/Classes'),
);
