services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  FriendsOfTYPO3\TtAddress\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'
   
  FriendsOfTYPO3\TtAddress\Command\GeocodeCommand:
    tags:
      - name: 'console.command'
        command: 'ttaddress:geocode'
        description: 'Geocode tt_address records'
        schedulable: true
        hidden: false
